version: "2"
checks:
  similar-code:
    enabled: false
exclude_patterns:
- "config/"
- "db/"
- "dist/"
- "features/"
- "**/node_modules/"
- "script/"
- "**/spec/"
- "**/test/"
- "**/tests/"
- "**/vendor/"
- "**/*.d.ts"
- "**/*.spec.ts"
- "client/src/karma.conf.js"
- "client/src/polyfills.ts"
