# ref: https://docs.codeclimate.com/docs/travis-ci-test-coverage#section-travis-ci-multiple-test-suites
# multiple tests suites
# working example can be found at https://github.com/scottohara/loot

language: ruby

cache:
  - bundler
  - npm

addons:
  chrome: stable

before_install:
  - nvm install lts/*
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

install:
  - bundle config set without 'development production'
  - bundle install
  - npm install

before_script:
  # dummy file for app.rb: File.read('./public/index.html')
  - mkdir ./public; touch ./public/index.html

script:
  - bundle exec rake
  - npm run lint
  - npm run test:headless -- --code-coverage
  # - npm run e2e
  - npm run build:prod

after_script:
  - ./cc-test-reporter format-coverage -t simplecov -o coverage/codeclimate.backend.json coverage/.resultset.json
  - ./cc-test-reporter format-coverage -t lcov -o coverage/codeclimate.frontend.json client/coverage/lcov.info
  - ./cc-test-reporter sum-coverage coverage/codeclimate.*.json -p 2
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi
